### ISSUE TITLE
cannot find w2v_200.txt

### ISSUE THREAD

**Issue by lyzy** [NUSTM/ECPE#1]
To run the model needs a embedding file named "w2v_200.txt". However, it isn't included in the repository and the description in the article is obscure:
We use word vectors that were pre-trained on the corpora from Chinese Weibo1 with word2vec
(Mikolov et al., 2013) toolkit.
The reference to the website: http://www.aihuang.org/p/challenge.html is invalid. Do you mean this embedding file is trained by yourselves? Otherwise, could you please provide this file in the repository? Thx!

**Comment by balancedzx** [comment]
The word embedding file "w2v_200.txt" is trained on the Chinese Weibo corpus by us and can be downloaded using the access code "m11h" from the following link: https://pan.baidu.com/s/1YTkk3QNdR51AX7N_aupHEQ

**Comment by lyzy** [comment]
> The word embedding file "w2v_200.txt" is trained on the Chinese Weibo corpus by us and can be downloaded using the access code "m11h" from the following link: https://pan.baidu.com/s/1YTkk3QNdR51AX7N_aupHEQ

**Comment by lyzy** [comment]
It works. thx!
