### ISSUE TITLE
Why run() execute twice?

### ISSUE THREAD

**Issue by lpq29743** [NUSTM/ECPE#2]
It's observed that the method `run()` has been executed twice. Is the twice execution just for getting a reliable result?

**Comment by balancedzx** [comment]
Yeah, the multiple executions of run () are independent, you can execute it as many times as you like

**Comment by bbruceyuan** [comment]
Yes. In this paper, the author mentions that `we repeat the experiments 20 times and report the average result`  and every execution of `run()` is ten folds.
