### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ZiruiYan** [NUSTM/ECPE#3]
The following error was found while running the code 
`FileNotFoundError: [Errno 2] No such file or directory: '../data/w2v_200.txt'`
I finally found data in RTHN,  maybe you can upload it.

In addition, could you explain what the files in data_combine are for?

**Comment by hxl523** [comment]
where is the data '../data/w2v_200.txt'?

**Comment by hxl523** [comment]
I find it. It's in NUSTM/RTHN: The code of IJCAI2019 paper "RTHN: A RNN-Transformer Hierarchical Network for Emotion Cause Extraction".  https://github.com/NUSTM/RTHN

**Comment by liuzhencheng** [comment]
> I find it. It's in NUSTM/RTHN: The code of IJCAI2019 paper "RTHN: A RNN-Transformer Hierarchical Network for Emotion Cause Extraction". https://github.com/NUSTM/RTHN

cool
